name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: gomlang/verification/.github/workflows/ecosystem-ci.yml@3f87220933b8513b2d832c10cf309f39e7aeb044
    with:
      module: xml
      verification-ref: 3f87220933b8513b2d832c10cf309f39e7aeb044
