name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: gomlang/verification/.github/workflows/ecosystem-ci.yml@f6e7df6693eed4a970c2a6ef441fb97f6ade9f04
    with:
      module: xml
      verification-ref: f6e7df6693eed4a970c2a6ef441fb97f6ade9f04
